@isTest
private class TestSFJiraConnectivity {
 
   // CRON expression: midnight on March 15.
   // Because this is a test, job executes
   // immediately after Test.stopTest().
   public static String CRON_EXP = '0 0 0 15 3 ? 2022';

   static testmethod void test() {
      Test.startTest();
        JIRA_CONFIG__c jiraConfig = new JIRA_CONFIG__c();
        jiraConfig.Name = 'CONFIG';
        jiraConfig.Public_Comment_Identifier__c = '#pub#';
        jiraConfig.Project_Name__c = 'MPSUPPORT';
       jiraConfig.alertsRecipient__c = 'skumar3@walmartlabs.com';
       
       jiraConfig.URL__c = 'https://jira.walmart.com';
       insert jiraConfig;
      // Schedule the test job
      String jobId = null;
       
        jobId = System.schedule('JIRAPoller',
                        CRON_EXP, 
                        new JIRAPoller());
              // Get the information from the CronTrigger API object
      CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
         NextFireTime
         FROM CronTrigger WHERE id = :jobId];

         
    
      // Verify the expressions are the same
      System.assertEquals(CRON_EXP, 
         ct.CronExpression);

      // Verify the job has not run
      System.assertEquals(0, ct.TimesTriggered);

      // Verify the next time the job will run
      System.assertEquals('2022-03-15 00:00:00', 
      String.valueOf(ct.NextFireTime));
     
      JIRAPoller.sendAlertEmail(jiraConfig);
      
      Test.stopTest();

      
   }
    

}